name: MyAction Get Details
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Print Hello world
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo "Author: ${{ github.actor }}"
          echo "Last Commit:"
          git log -1 --pretty=%B
          echo "Changes between the last commit and the default branch:"
          branch_name="${{ github.event.pull_request.head.ref }}"
          git checkout origin/"${branch_name}"
          git diff origin/main     
